### ISSUE TITLE
Extra Utilities 1.1.0c + Ex Nihilo Omnia = Deep Dark will freeze your server/client

### ISSUE THREAD

**Issue by Xiaminou** [rwtema/extrautilities_old_issues#1030]
After updating a number of mods I found that my server would freeze even with a fresh new world, and that dimension -11325 is responsible, I tracked it down to EUs.
However EUs alone will not cause any problems, I have tracked it down and it's Ex Nihilo Omnia having bad interaction with Extra Utilities' Deep Dark.

Mod List: http://pastebin.com/CMTNKDsi
Server Lag: http://pastebin.com/HbqmeZbV (this is only about 20s after the server starts, it keeps rising, after a couple of minutes it's 2000ms a tick)

https://github.com/Jozufozu/ExNihiloOmnia/issues/57

**Comment by Ristellise** [comment]
I also agree on this one. both mods together will cause memory to increase and increase till it crashes.

**Comment by jikuja** [comment]
I saw similar problem. User had edited his FTB Unstable and got following result: http://pastebin.com/wiLGY9vN (Notice harvestcraft here and in OP's log). Part of the problem seems to be caused by harvestcraft and actually adddition: https://github.com/Ellpeck/ActuallyAdditions/issues/275

I tested newest installing only XU2 and ex nihilo omnia. Got serious problems with combination but could not get any sane log or thread dump to find root cause of the problem. Only thing I saw was that Ex nihilo omnia's PositionHelper.hasNearbyWaterSource() triggers chunk creations.

**Comment by DatrixTHLK** [comment]
I've been getting this very same error and still don't understand it. I thought it had to do with chickenbones chunk loader mod.  EU is causing extreme amounts of block lag and freezing up entities in my game. I've tested the game with ExtraUtils 2 and without. With EU2 the game is very lag prone, so much so, that the time in game is rubber-banding back and forth and the blocks I break keep reappearing for several minutes. Without it the game works as it normally should. Until this gets fixed, I will have to let this mod go. 1.2.0 Alpha build of this mod

**Comment by Mattsingen** [comment]
I've suffered this problem, my current solution is to back down to XU2 v1.0.1
This indicates that the problem comes from a change in XU2, but it might not show if you don't have other mods installed.

**Comment by DatrixTHLK** [comment]
I will have to do so...Well for you Newest build of Optifine will correct the issues of 1.1.0. The only issue I have is this specific one is **NOT** Optifine's problem. I just hope the mod author will correct this.

You are correct since this mod doesn't cooperate with Optifine It will give out an error saying Optifine is installed and isn't supported. Optifine **ISN'T** the true issue.

**Comment by DatrixTHLK** [comment]
Has the issue been fixed in 1.2.2? @Mattsingen

**Comment by Mattsingen** [comment]
I haven't tested. Will hopefully test it tonight. I'll report back if I still have the problem with the latest build.

**Comment by Mattsingen** [comment]
I've now tested, but with the setting "Deep Dark"=false 
It's working as expected. 
Due to some changes in my private pack I've started a new world, so there isn't any deep dark dimension in my world. So I'm not sure if it's totally fixed or if it's just working without deep dark.
