### ISSUE TITLE
Crash Quantum Quarry Biome marker hell

### ISSUE THREAD

**Issue by Gohu29** [rwtema/extrautilities_old_issues#1453]
When I use Biome Marker Hell the serveur crash.
Crash Repport:
https://pastebin.com/m8fXV1ZW

extrautils2-1.10.2-1.3.0
SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
SpongeForge: 1.10.2-2254-5.2.0-BETA-2236
Minecraft Forge: 12.18.3.2254

If you need more ask me.
Thanks for reading.

**Comment by lurr** [comment]
Update Extra Utilities - this is fixed in later versions.

**Comment by ResqDiver1317** [comment]
We updated our Beyond pack and now are running the ExtraUtils2 1.10.2-1.4.4 and the Hell Marker crash is still an issue.

**Comment by bgsteiner** [comment]
I can also confirm after updating Infinity Lite we have the crash issue. It also appears to happen with the End marker but for a different reason.
