### ISSUE TITLE
Crusher Dupe

### ISSUE THREAD

**Issue by TheLimePixel** [rwtema/extrautilities_old_issues#1741]
When shift-clicking items out of a Crusher, the progress bar keeps going allowing you to essentially dupe items.

**Comment by JoeSGT** [comment]
can confirm this does dupe 
versions that i am currently on is
Forge: 14.23.0.2529
ExtraUtilities: 1.12-1.6.5

**Comment by TheLimePixel** [comment]
It's with every ExU machine actually.

**Comment by JoeSGT** [comment]
This issue fixed with EU - 1.6.6

**Comment by Ar4093** [comment]
This still happens in 1.6.6, although only with the Resonator.
