### ISSUE TITLE
ChunkCache cannot be cast to net.minecraft.world crash

### ISSUE THREAD

**Issue by Donkazi** [rwtema/extrautilities_old_issues#254]
I am playing Bevo's techpack, and i just updated it. But when i tried to join my world, it kept crashing, and i could see that carpenters block did something wrong in the crash report, but i didnt know what it did.. But i fixed it by removing Carpenter's blocks, but that's not what i wanted.

Here is the crash report: http://pastebin.com/Ujw1KDhg

(I got redirected to here by Mineshopper, Carpenter's Blocks)

**Comment by rwtema** [comment]
Fixed in 1.1.0h

**Comment by Donkazi** [comment]
Im sorry, but apparently not. I just updated to 1.1.0h, but still gets the crash. I can use any other blocks, just not Extra Utilities blocks.
