### ISSUE TITLE
8x and 64x nether star generators limited to 100,000 RF/t

### ISSUE THREAD

**Issue by brandon3055** [rwtema/extrautilities_old_issues#453]
Decided to re post this issue with more supporting information since my original issue got completely ignored (sorry if you just haddent got to it yet)

Correct me if im wrong but the way the generators work is one unit of fuel e.g. coal, redstone bucket, lava bucket, nether star should generate the same amount of power in all 3 tiers of generator just at 1,8 and 64 times the speed.

This seems to be correct for all generators except the nether star generator which instead generates
96M 1x
30M 8x
3.8M 64x
The storage i am using to test this can recive of over 2 billion RF/t so its definitely not a case of not being able to receive the amount of power being generated.

I would really like to see this fixed im guessing its just a cap in the code somewhere that needs to be increased so it shouldn't be too hard to fix.

(some time later)
After looking through the eu code i believe i found the problem {tech talk incoming}
(this is in the TileEntityGenerator class)
The storage field is initialized with

public EnergyStorage storage = new EnergyStorage(100000);

This sets the capacity and max transfer to 100000 Then the capacity is modified using

this.storage.setCapacity(100000 \* getMultiplier());

This increases the capacity but it dose not increase the max transfer rate. To fix this you would simply have to increase the max receive & max extract in the same way (max receive needs to be increased because it caps the generation rate)

Im not familiar with the EU code at all so i cant be 100% sure but i am familiar with the RF API so i am pretty sure that is the problem. (and sorry if i did a horrible job of explaining that im ok at writing code but not so good at explaining it)

Hope this helps and would really like a reply this time please.

**Comment by Piddu** [comment]
Noticed the same issue 12 days ago and made same tests.
I think this makes clear where the problem is, so the transfer rate is capped no matter what you put on the output to receive the power.

**Comment by Piddu** [comment]
i've just read the changelog in latest version 1.2.1:
"Generator buffer is now 100,000RF \* multiplier"
I suppose the 1x generator's multiplier is 0.4
The 8x should be 3.2
The 64x should be 25.6
with these values everything should be ok.

**Comment by brandon3055** [comment]
The buffer is how much energy the generator can store it is not the transfer rate. And 1.2.1 is the version i tested with and the version i decompiled to locate the error i mentioned above.

**Comment by Piddu** [comment]
Yea i've confused the two things, the internal buffer values are set properly.
Can you post the formula implemented for the transfer rate?

**Comment by brandon3055** [comment]
The transfer rate is set using 

transferLimit() \* getMultiplier() (transferLimit returns storage capacity)

So its trying to extract the correct amount of energy but the storage is capped at 100,000

**Comment by brandon3055** [comment]
After seeing this
rwtema said "No point in fixing this. You would never need a 64x generator."
in #303

I decided to just create a simple mod that fixes the problem. Here it is if anyone else wants to use it
https://drive.google.com/file/d/0B0fqrOj7BGp1QnFQRks3ZXZ0dlk/view?usp=sharing

All it dose is tell BlockGenerator to use my own version of TileEntityGeneratorNether (that fixes the problem) when it creates a tile entity for a nether star generator.

**Comment by OMGHannahMontana** [comment]
Just needed to thank you for this. I was making a nether star farm and had the 64x generator ready to plug in just to find out the max output is 100k :/ Your fix only ups the max output to 2.5mil RF/t vs the 5mil RF/t that theoretically you should get but either way, Thanks!

**Comment by brandon3055** [comment]
I can check it again but im pretty sure the math works out to 2.5m RF/t

Edit: I think i see your confusion. The wiki says that the nether star gen used to produce 40k RF/t and was changed to 81k in 1.7.10. But in reality i think its the other way around because according to the gui it generates 40,000 and  64 \* 40,000 = 2,560,000

**Comment by OMGHannahMontana** [comment]
Ah, well if that's the truth then I'm disappointed. I was looking forward to one nether star giving me a billion rf. Thanks for the clarification though.

**Comment by cortices** [comment]
If anyone is still wondering about this, version 1.2.7 should fix this according to changelog. It took Direwolf20 making a 64x generator on Forgecraft2 for RWTema to decide it is worth fixing.
http://minecraft.curseforge.com/mc-mods/225561-extra-utilities/files/2245576

**Comment by TherminatorX** [comment]
Note to self: If you want an ExU bug fixed, don't post it on here: tell the Forgecraft guys to use it to annoy Tema.

**Comment by callous4567** [comment]
Still not able to get more than 100k RF/t out, on latest version too ;_;
